export const GET_ERRORS = "GET_ERRORS";
export const GET_PERSONS = "GET_PERSONS";
export const GET_PERSON = "GET_PERSON";


export const SET_CURRENT_USER = "SET_CURRENT_USER";


export const GET_ALLBOOKS = "GET_ALLBOOKS";
export const GET_BOOKS = "GET_BOOKS";
export const GET_BOOK = "GET_BOOK";

export const GET_CATEGORIES = "GET_CATEGORIES";

export const GET_ALLREVIEWS = "GET_ALLREVIEWS";
export const GET_REVIEWS = "GET_REVIEWS";
export const GET_REVIEW = "GET_REVIEW";

export const GET_ALL_CART_ITEMS = "GET_ALL_CART_ITEMS";
export const GET_CART_ITEMS = "GET_CART_ITEMS";

export const GET_VALIDATED_USERS = "GET_VALIDATED_USERS";
export const GET_BLOCKED_USERS = "GET_BLOCKED_USERS";
export const GET_PENDING_USERS = "GET_PENDING_USERS";