version: "3.8"
services:

  loginmicroservices:
    build:
      context: BackEnd/loginmicroservices
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend
      - frontend  

  bookmicroservices:
    build:
      context: BackEnd/bookmicroservices
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    networks:
      - backend
      - frontend

  reviewmicroservices:
    build:
      context: BackEnd/reviewmicroservices
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always
    networks:
      - backend
      - frontend  

  cartmicroservice:
    build:
      context: BackEnd/cartmicroservice
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: always
    networks:
      - backend
      - frontend  

  myfirstapp:
    build:
      context: FrontEnd/myfirstapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - bookmicroservices
      - loginmicroservices
      - reviewmicroservices
      - cartmicroservice

    networks:
      - frontend  

networks:
  backend:
  frontend:    
